services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --url http://infra:80
    environment:
      - TUNNEL_TOKEN=${CLOULDFLARE_TUNNEL_ID}
    networks:
      - app-net

  frontend:
    image: ghcr.io/mateus-ms/xeubiart-frontend:${IMAGE_TAG:-latest}
    container_name: frontend
    build:
      context: ../../frontend/templ
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-net
    restart: unless-stopped

  infra:
    image: ghcr.io/mateus-ms/xeubiart-infra:${IMAGE_TAG:-latest}
    container_name: infra
    build:
      context: ../../
      dockerfile: infra/caddy/Dockerfile
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ../caddy/Caddyfile.${APP_ENV:-prod}:/etc/caddy/Caddyfile
      - ../../frontend/static:/app/static
    depends_on:
      - frontend
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge