services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run --url http://infra:80
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOULDFLARE_TUNNEL_TOKEN}
    networks:
      - app-net

  frontend:
    image: ghcr.io/mateus-ms/xeubiart-frontend:latest
    container_name: frontend
    build:
      context: ../../frontend/templ
      dockerfile: Dockerfile
    networks:
      - app-net
    restart: unless-stopped

  infra:
    image: ghcr.io/mateus-ms/xeubiart-infra:latest
    container_name: infra
    build:
      context: ../../
      dockerfile: infra/caddy/Dockerfile
    volumes:
      - ../caddy/Caddyfile.${APP_ENV:-prod}:/etc/caddy/Caddyfile
      - ../../frontend/static:/app/static
    depends_on:
      - frontend
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge