// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package desktop_page_register

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	desktop_components_inputs "github.com/Mateus-MS/Xeubiart.git/frontend/desktop/components/inputs/defaultInput"
	desktop_components "github.com/Mateus-MS/Xeubiart.git/frontend/desktop/components/loginOptions"
)

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Document</title><base href=\"static/desktop/pages/register/\"><link rel=\"stylesheet\" href=\"../../../asset/css/main.css\" type=\"text/css\"><link rel=\"stylesheet\" href=\"css/main.css\" type=\"text/css\"><link rel=\"stylesheet\" href=\"css/registerForm.css\" type=\"text/css\"><link rel=\"stylesheet\" href=\"css/stepDisplay.css\" type=\"text/css\"><link rel=\"stylesheet\" href=\"css/controller.css\" type=\"text/css\"></head><body><section id=\"main_section\"><div id=\"side_word\"><a href=\"/\"><img src=\"../../../asset/svg/logo.svg\"></a> <span>REGISTER</span></div><div id=\"image_container\"><img src=\"img/pereco_register.png\"><h3>Why do i need an account?</h3><p>Your XeubiArt account grants you several exclusive benefits, such as discounts, a loyalty program, and greater convenience. In addition, you can access your invoices and high-quality photos of your tattoos at any time.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = RegisterForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</section></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func RegisterForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"register_form\" data-step=\"1\"><div id=\"step-display\"><div class=\"step\" id=\"step-display-1\"><div class=\"number\">1</div><span class=\"label\">Basic informations</span></div><div class=\"step\" id=\"step-display-2\"><div class=\"number\">2</div><span class=\"label\">Contact informations</span></div><div class=\"step\" id=\"step-display-3\"><div class=\"number\">3</div><span class=\"label\">Safety informations</span></div></div><div id=\"step-inputs\"><div class=\"steps-holder\" id=\"step-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"100%",
			"Full name",
			[]desktop_components_inputs.InputModel{
				{Type: "text", Placeholder: "Type your full name"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"100%",
			"Password",
			[]desktop_components_inputs.InputModel{
				{Type: "password", Placeholder: "Type your password"},
				{Type: "password", Placeholder: "Confirm your password"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div class=\"steps-holder\" id=\"step-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"100%",
			"E-mail",
			[]desktop_components_inputs.InputModel{
				{Type: "email", Placeholder: "Type your E-mail"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"100%",
			"Phone",
			[]desktop_components_inputs.InputModel{
				{Type: "text", Placeholder: "Type your phone number"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"40%",
			"Age",
			[]desktop_components_inputs.InputModel{
				{Type: "number", Placeholder: "Type your age"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"50%",
			"Pronoum",
			[]desktop_components_inputs.InputModel{
				{Type: "text", Placeholder: "What's your pronoum"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"steps-holder\" id=\"step-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components_inputs.DefaultInput(
			"100%",
			"Emergency contact",
			[]desktop_components_inputs.InputModel{
				{Type: "text", Placeholder: "Type your emergency contact number"},
			},
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"custom-input\" style=\"width: 100%;\"><span>Allergies</span><fieldset><label><input type=\"checkbox\" value=\"latex\"> Látex (Gloves, elastics, etc)</label> <label><input type=\"checkbox\" value=\"metals\"> Metals (nickel, chromium, cobalt, mercury, iron)</label> <label><input type=\"checkbox\" value=\"cleaning\"> Skin cleansing products (alcohol, antiseptic soaps, disinfectants)</label></fieldset></div><div class=\"custom-input\" style=\"width: 100%;\"><span>Additional information</span> <textarea placeholder=\"Any important thing i should be aware of\"></textarea></div></div></div><div class=\"step-controller\"><button id=\"next-step\" class=\"btn\" disabled>Next step</button> <button id=\"prev-step\" class=\"btn\">Previous step</button></div><div id=\"optionally\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = desktop_components.LoginOptions().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div id=\"complete-registration-later\"><button>Complete profile later</button><p>You can optionally answer these questions later to speed up your registration now.</p></div></div><span id=\"login-redirection\">Already have an account? <a href=\"/login\">Login</a></span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
