spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER:${DB_USERNAME}}
spring.datasource.password=${POSTGRES_PASS:${DB_PASSWORD}}

app.storage.root=/app/uploads

spring.jpa.hibernate.ddl-auto=update